profile: full

ceip_policy_disclosed: true # Installation fails if this is set to 'false'
buildservice:
  kp_default_repository: "harbor.tanzukr.com/tanzu-application-platform/build-service"
  kp_default_repository_username: "admin"
  kp_default_repository_password: "VMware1!"
  enable_automatic_dependency_updates: false
  exclude_dependencies: true
  ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDwzCCAqugAwIBAgIUUWdX02WTOTFwA0EW+HvwHzN5/k8wDQYJKoZIhvcNAQEN
          BQAwZTELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5n
          bmFtMQ4wDAYDVQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rh
          bnp1a3IuY29tMB4XDTIyMDkxNjA2MTk1N1oXDTMyMDkxMzA2MTk1N1owZTELMAkG
          A1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5nbmFtMQ4wDAYD
          VQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rhbnp1a3IuY29t
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSyGmTQVvD6J+YtFUkO5
          j/SSi8onaxvmGVYCuS6l7y7k9HJj48ASctzl3K65ePCuKanLNaATrpqyC6B8Ywhl
          /UJxukz5z6GrdguCJiSEBQnKPdVq9bn3Tu8v9JWzk4UcRFRU9GWnWRul6w1pM/ms
          xnodNb9rhebvJ2GndhkBoP9FQE/gF7cp2wjcpMCcrBLKcqZW/TuGkZHMF+eAXWDs
          +t5XIdteJLRpfLVYQxBxKh1JhWdUONC+2B1vt5mm8I1xgasXa+MF0s2RMQTu99/V
          KRQnmEpi9Bc/v2H/Ub2PClQwL1crTelmMbVtZA9uR51qBkHOUfGWSEpXEGZEIqFN
          iwIDAQABo2swaTAdBgNVHQ4EFgQU5ujIZAe0J3MoJQjaQdJloxHOXeYwHwYDVR0j
          BBgwFoAU5ujIZAe0J3MoJQjaQdJloxHOXeYwDwYDVR0TAQH/BAUwAwEB/zAWBgNV
          HREEDzANggt0YW56dWtyLmNvbTANBgkqhkiG9w0BAQ0FAAOCAQEAhZMa+lDMKGoE
          wiN5viqUbZ9/jptR3sS6Vtr0AkEPPq0r/JXbKPWlmZYmYbhAdE2l5pAzKJJ+/hl3
          +6uZftK4aSAFd5YFkDVqkHA1yWN3IARHJBrJ1MjXmnS7qqPJKE1dgmKsrS+0qvl9
          EkMfoQvVGcDG/+gc8u9EhDZZpEsVyCdajTQIojnm9W8Ut/pf0idw8TgDhukWDtAt
          JYLPpCV9R1StN35zdLHsP097X24LPEqTF/ulB7zmwTLmejWXl/WWuiXgs+v4fd+Z
          EKaXUumX4rIj2WWNMYlY8lpQb7JhS5zfaVegVe1/UqzmQz0XmZYiG95Y4gFV1+DO
          4aCJxMz52w==
          -----END CERTIFICATE-----

scanning:
  metadataStore:
    url: ""
    
accelerator:
  domain: tanzukr.com
  samples:
  # Prevent repeated polling of github to pull accelerators
    include: true

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "harbor.tanzukr.com"
    repository: "tanzu-application-platform/supply-chain"
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: "learning.tanzukr.com"
  ingressClass: contour
  ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDwzCCAqugAwIBAgIUUWdX02WTOTFwA0EW+HvwHzN5/k8wDQYJKoZIhvcNAQEN
          BQAwZTELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5n
          bmFtMQ4wDAYDVQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rh
          bnp1a3IuY29tMB4XDTIyMDkxNjA2MTk1N1oXDTMyMDkxMzA2MTk1N1owZTELMAkG
          A1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5nbmFtMQ4wDAYD
          VQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rhbnp1a3IuY29t
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSyGmTQVvD6J+YtFUkO5
          j/SSi8onaxvmGVYCuS6l7y7k9HJj48ASctzl3K65ePCuKanLNaATrpqyC6B8Ywhl
          /UJxukz5z6GrdguCJiSEBQnKPdVq9bn3Tu8v9JWzk4UcRFRU9GWnWRul6w1pM/ms
          xnodNb9rhebvJ2GndhkBoP9FQE/gF7cp2wjcpMCcrBLKcqZW/TuGkZHMF+eAXWDs
          +t5XIdteJLRpfLVYQxBxKh1JhWdUONC+2B1vt5mm8I1xgasXa+MF0s2RMQTu99/V
          KRQnmEpi9Bc/v2H/Ub2PClQwL1crTelmMbVtZA9uR51qBkHOUfGWSEpXEGZEIqFN
          iwIDAQABo2swaTAdBgNVHQ4EFgQU5ujIZAe0J3MoJQjaQdJloxHOXeYwHwYDVR0j
          BBgwFoAU5ujIZAe0J3MoJQjaQdJloxHOXeYwDwYDVR0TAQH/BAUwAwEB/zAWBgNV
          HREEDzANggt0YW56dWtyLmNvbTANBgkqhkiG9w0BAQ0FAAOCAQEAhZMa+lDMKGoE
          wiN5viqUbZ9/jptR3sS6Vtr0AkEPPq0r/JXbKPWlmZYmYbhAdE2l5pAzKJJ+/hl3
          +6uZftK4aSAFd5YFkDVqkHA1yWN3IARHJBrJ1MjXmnS7qqPJKE1dgmKsrS+0qvl9
          EkMfoQvVGcDG/+gc8u9EhDZZpEsVyCdajTQIojnm9W8Ut/pf0idw8TgDhukWDtAt
          JYLPpCV9R1StN35zdLHsP097X24LPEqTF/ulB7zmwTLmejWXl/WWuiXgs+v4fd+Z
          EKaXUumX4rIj2WWNMYlY8lpQb7JhS5zfaVegVe1/UqzmQz0XmZYiG95Y4gFV1+DO
          4aCJxMz52w==
          -----END CERTIFICATE-----

appliveview:
  ingressEnabled: true

appliveview_connector:
  backend:
    ingressEnabled: true

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "tanzukr.com"
  app_config:
    app:
      baseUrl: http://tap-gui.tanzukr.com
    catalog:
      locations:
        - type: url
          target: https://github.com/shimirooinfo/TAP-HOL/blob/main/catalog/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.tanzukr.com
      cors:
        origin: http://tap-gui.tanzukr.com
          
metadata_store:
  ingress_domain: "tanzukr.com"
  app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
  ingress_enabled: "true"
  ns_for_export_app_cert: "default"
  targetImagePullSecret: "tap-registry"
  ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDwzCCAqugAwIBAgIUUWdX02WTOTFwA0EW+HvwHzN5/k8wDQYJKoZIhvcNAQEN
          BQAwZTELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5n
          bmFtMQ4wDAYDVQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rh
          bnp1a3IuY29tMB4XDTIyMDkxNjA2MTk1N1oXDTMyMDkxMzA2MTk1N1owZTELMAkG
          A1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5nbmFtMQ4wDAYD
          VQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rhbnp1a3IuY29t
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSyGmTQVvD6J+YtFUkO5
          j/SSi8onaxvmGVYCuS6l7y7k9HJj48ASctzl3K65ePCuKanLNaATrpqyC6B8Ywhl
          /UJxukz5z6GrdguCJiSEBQnKPdVq9bn3Tu8v9JWzk4UcRFRU9GWnWRul6w1pM/ms
          xnodNb9rhebvJ2GndhkBoP9FQE/gF7cp2wjcpMCcrBLKcqZW/TuGkZHMF+eAXWDs
          +t5XIdteJLRpfLVYQxBxKh1JhWdUONC+2B1vt5mm8I1xgasXa+MF0s2RMQTu99/V
          KRQnmEpi9Bc/v2H/Ub2PClQwL1crTelmMbVtZA9uR51qBkHOUfGWSEpXEGZEIqFN
          iwIDAQABo2swaTAdBgNVHQ4EFgQU5ujIZAe0J3MoJQjaQdJloxHOXeYwHwYDVR0j
          BBgwFoAU5ujIZAe0J3MoJQjaQdJloxHOXeYwDwYDVR0TAQH/BAUwAwEB/zAWBgNV
          HREEDzANggt0YW56dWtyLmNvbTANBgkqhkiG9w0BAQ0FAAOCAQEAhZMa+lDMKGoE
          wiN5viqUbZ9/jptR3sS6Vtr0AkEPPq0r/JXbKPWlmZYmYbhAdE2l5pAzKJJ+/hl3
          +6uZftK4aSAFd5YFkDVqkHA1yWN3IARHJBrJ1MjXmnS7qqPJKE1dgmKsrS+0qvl9
          EkMfoQvVGcDG/+gc8u9EhDZZpEsVyCdajTQIojnm9W8Ut/pf0idw8TgDhukWDtAt
          JYLPpCV9R1StN35zdLHsP097X24LPEqTF/ulB7zmwTLmejWXl/WWuiXgs+v4fd+Z
          EKaXUumX4rIj2WWNMYlY8lpQb7JhS5zfaVegVe1/UqzmQz0XmZYiG95Y4gFV1+DO
          4aCJxMz52w==
          -----END CERTIFICATE-----

grype:
  namespace: "default" # (optional) Defaults to default namespace.
  targetImagePullSecret: "registry-credentials"

cnrs:
  domain_name: tanzukr.com
  ingress:
    reuse_crds: true
    external:
      namespace: tanzu-system-ingress

contour:
  envoy:
    service:
      type: LoadBalancer

source_controller:
  ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDwzCCAqugAwIBAgIUUWdX02WTOTFwA0EW+HvwHzN5/k8wDQYJKoZIhvcNAQEN
          BQAwZTELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5n
          bmFtMQ4wDAYDVQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rh
          bnp1a3IuY29tMB4XDTIyMDkxNjA2MTk1N1oXDTMyMDkxMzA2MTk1N1owZTELMAkG
          A1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5nbmFtMQ4wDAYD
          VQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rhbnp1a3IuY29t
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSyGmTQVvD6J+YtFUkO5
          j/SSi8onaxvmGVYCuS6l7y7k9HJj48ASctzl3K65ePCuKanLNaATrpqyC6B8Ywhl
          /UJxukz5z6GrdguCJiSEBQnKPdVq9bn3Tu8v9JWzk4UcRFRU9GWnWRul6w1pM/ms
          xnodNb9rhebvJ2GndhkBoP9FQE/gF7cp2wjcpMCcrBLKcqZW/TuGkZHMF+eAXWDs
          +t5XIdteJLRpfLVYQxBxKh1JhWdUONC+2B1vt5mm8I1xgasXa+MF0s2RMQTu99/V
          KRQnmEpi9Bc/v2H/Ub2PClQwL1crTelmMbVtZA9uR51qBkHOUfGWSEpXEGZEIqFN
          iwIDAQABo2swaTAdBgNVHQ4EFgQU5ujIZAe0J3MoJQjaQdJloxHOXeYwHwYDVR0j
          BBgwFoAU5ujIZAe0J3MoJQjaQdJloxHOXeYwDwYDVR0TAQH/BAUwAwEB/zAWBgNV
          HREEDzANggt0YW56dWtyLmNvbTANBgkqhkiG9w0BAQ0FAAOCAQEAhZMa+lDMKGoE
          wiN5viqUbZ9/jptR3sS6Vtr0AkEPPq0r/JXbKPWlmZYmYbhAdE2l5pAzKJJ+/hl3
          +6uZftK4aSAFd5YFkDVqkHA1yWN3IARHJBrJ1MjXmnS7qqPJKE1dgmKsrS+0qvl9
          EkMfoQvVGcDG/+gc8u9EhDZZpEsVyCdajTQIojnm9W8Ut/pf0idw8TgDhukWDtAt
          JYLPpCV9R1StN35zdLHsP097X24LPEqTF/ulB7zmwTLmejWXl/WWuiXgs+v4fd+Z
          EKaXUumX4rIj2WWNMYlY8lpQb7JhS5zfaVegVe1/UqzmQz0XmZYiG95Y4gFV1+DO
          4aCJxMz52w==
          -----END CERTIFICATE-----

convention_controller:
  ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDwzCCAqugAwIBAgIUUWdX02WTOTFwA0EW+HvwHzN5/k8wDQYJKoZIhvcNAQEN
          BQAwZTELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5n
          bmFtMQ4wDAYDVQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rh
          bnp1a3IuY29tMB4XDTIyMDkxNjA2MTk1N1oXDTMyMDkxMzA2MTk1N1owZTELMAkG
          A1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5nbmFtMQ4wDAYD
          VQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rhbnp1a3IuY29t
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSyGmTQVvD6J+YtFUkO5
          j/SSi8onaxvmGVYCuS6l7y7k9HJj48ASctzl3K65ePCuKanLNaATrpqyC6B8Ywhl
          /UJxukz5z6GrdguCJiSEBQnKPdVq9bn3Tu8v9JWzk4UcRFRU9GWnWRul6w1pM/ms
          xnodNb9rhebvJ2GndhkBoP9FQE/gF7cp2wjcpMCcrBLKcqZW/TuGkZHMF+eAXWDs
          +t5XIdteJLRpfLVYQxBxKh1JhWdUONC+2B1vt5mm8I1xgasXa+MF0s2RMQTu99/V
          KRQnmEpi9Bc/v2H/Ub2PClQwL1crTelmMbVtZA9uR51qBkHOUfGWSEpXEGZEIqFN
          iwIDAQABo2swaTAdBgNVHQ4EFgQU5ujIZAe0J3MoJQjaQdJloxHOXeYwHwYDVR0j
          BBgwFoAU5ujIZAe0J3MoJQjaQdJloxHOXeYwDwYDVR0TAQH/BAUwAwEB/zAWBgNV
          HREEDzANggt0YW56dWtyLmNvbTANBgkqhkiG9w0BAQ0FAAOCAQEAhZMa+lDMKGoE
          wiN5viqUbZ9/jptR3sS6Vtr0AkEPPq0r/JXbKPWlmZYmYbhAdE2l5pAzKJJ+/hl3
          +6uZftK4aSAFd5YFkDVqkHA1yWN3IARHJBrJ1MjXmnS7qqPJKE1dgmKsrS+0qvl9
          EkMfoQvVGcDG/+gc8u9EhDZZpEsVyCdajTQIojnm9W8Ut/pf0idw8TgDhukWDtAt
          JYLPpCV9R1StN35zdLHsP097X24LPEqTF/ulB7zmwTLmejWXl/WWuiXgs+v4fd+Z
          EKaXUumX4rIj2WWNMYlY8lpQb7JhS5zfaVegVe1/UqzmQz0XmZYiG95Y4gFV1+DO
          4aCJxMz52w==
          -----END CERTIFICATE-----

cartographer:
  ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDwzCCAqugAwIBAgIUUWdX02WTOTFwA0EW+HvwHzN5/k8wDQYJKoZIhvcNAQEN
          BQAwZTELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5n
          bmFtMQ4wDAYDVQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rh
          bnp1a3IuY29tMB4XDTIyMDkxNjA2MTk1N1oXDTMyMDkxMzA2MTk1N1owZTELMAkG
          A1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5nbmFtMQ4wDAYD
          VQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rhbnp1a3IuY29t
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSyGmTQVvD6J+YtFUkO5
          j/SSi8onaxvmGVYCuS6l7y7k9HJj48ASctzl3K65ePCuKanLNaATrpqyC6B8Ywhl
          /UJxukz5z6GrdguCJiSEBQnKPdVq9bn3Tu8v9JWzk4UcRFRU9GWnWRul6w1pM/ms
          xnodNb9rhebvJ2GndhkBoP9FQE/gF7cp2wjcpMCcrBLKcqZW/TuGkZHMF+eAXWDs
          +t5XIdteJLRpfLVYQxBxKh1JhWdUONC+2B1vt5mm8I1xgasXa+MF0s2RMQTu99/V
          KRQnmEpi9Bc/v2H/Ub2PClQwL1crTelmMbVtZA9uR51qBkHOUfGWSEpXEGZEIqFN
          iwIDAQABo2swaTAdBgNVHQ4EFgQU5ujIZAe0J3MoJQjaQdJloxHOXeYwHwYDVR0j
          BBgwFoAU5ujIZAe0J3MoJQjaQdJloxHOXeYwDwYDVR0TAQH/BAUwAwEB/zAWBgNV
          HREEDzANggt0YW56dWtyLmNvbTANBgkqhkiG9w0BAQ0FAAOCAQEAhZMa+lDMKGoE
          wiN5viqUbZ9/jptR3sS6Vtr0AkEPPq0r/JXbKPWlmZYmYbhAdE2l5pAzKJJ+/hl3
          +6uZftK4aSAFd5YFkDVqkHA1yWN3IARHJBrJ1MjXmnS7qqPJKE1dgmKsrS+0qvl9
          EkMfoQvVGcDG/+gc8u9EhDZZpEsVyCdajTQIojnm9W8Ut/pf0idw8TgDhukWDtAt
          JYLPpCV9R1StN35zdLHsP097X24LPEqTF/ulB7zmwTLmejWXl/WWuiXgs+v4fd+Z
          EKaXUumX4rIj2WWNMYlY8lpQb7JhS5zfaVegVe1/UqzmQz0XmZYiG95Y4gFV1+DO
          4aCJxMz52w==
          -----END CERTIFICATE-----
shared:
  ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDwzCCAqugAwIBAgIUUWdX02WTOTFwA0EW+HvwHzN5/k8wDQYJKoZIhvcNAQEN
          BQAwZTELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5n
          bmFtMQ4wDAYDVQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rh
          bnp1a3IuY29tMB4XDTIyMDkxNjA2MTk1N1oXDTMyMDkxMzA2MTk1N1owZTELMAkG
          A1UEBhMCS1IxDjAMBgNVBAgMBVNFT1VMMRAwDgYDVQQHDAdHYW5nbmFtMQ4wDAYD
          VQQKDAVUYW56dTEOMAwGA1UECwwFTUFQQlUxFDASBgNVBAMMC3Rhbnp1a3IuY29t
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSyGmTQVvD6J+YtFUkO5
          j/SSi8onaxvmGVYCuS6l7y7k9HJj48ASctzl3K65ePCuKanLNaATrpqyC6B8Ywhl
          /UJxukz5z6GrdguCJiSEBQnKPdVq9bn3Tu8v9JWzk4UcRFRU9GWnWRul6w1pM/ms
          xnodNb9rhebvJ2GndhkBoP9FQE/gF7cp2wjcpMCcrBLKcqZW/TuGkZHMF+eAXWDs
          +t5XIdteJLRpfLVYQxBxKh1JhWdUONC+2B1vt5mm8I1xgasXa+MF0s2RMQTu99/V
          KRQnmEpi9Bc/v2H/Ub2PClQwL1crTelmMbVtZA9uR51qBkHOUfGWSEpXEGZEIqFN
          iwIDAQABo2swaTAdBgNVHQ4EFgQU5ujIZAe0J3MoJQjaQdJloxHOXeYwHwYDVR0j
          BBgwFoAU5ujIZAe0J3MoJQjaQdJloxHOXeYwDwYDVR0TAQH/BAUwAwEB/zAWBgNV
          HREEDzANggt0YW56dWtyLmNvbTANBgkqhkiG9w0BAQ0FAAOCAQEAhZMa+lDMKGoE
          wiN5viqUbZ9/jptR3sS6Vtr0AkEPPq0r/JXbKPWlmZYmYbhAdE2l5pAzKJJ+/hl3
          +6uZftK4aSAFd5YFkDVqkHA1yWN3IARHJBrJ1MjXmnS7qqPJKE1dgmKsrS+0qvl9
          EkMfoQvVGcDG/+gc8u9EhDZZpEsVyCdajTQIojnm9W8Ut/pf0idw8TgDhukWDtAt
          JYLPpCV9R1StN35zdLHsP097X24LPEqTF/ulB7zmwTLmejWXl/WWuiXgs+v4fd+Z
          EKaXUumX4rIj2WWNMYlY8lpQb7JhS5zfaVegVe1/UqzmQz0XmZYiG95Y4gFV1+DO
          4aCJxMz52w==
          -----END CERTIFICATE-----
